=== nowackia/yad2/trunk/src/dune.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/dune"
	attributeFormDefault="qualified"
	xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.example.org/dune"
	elementFormDefault="qualified">

	<complexType name="UnitData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="Name" type="string" />
			<element name="BaseType" type="string" />
			<element name="Cost" type="string" />
			<element name="FireRange" type="string" />
			<element name="Speed" type="string" />
			<element name="ReloadTime" type="string" />
			<element name="AmmoType" type="string" />
			<element name="Health" type="string" />
			<element name="ViewRange" type="string" />
			<element name="Power" type="string" />
			<element name="BuildSpeed" type="string" />
			<element name="DamageDestroy" type="string" />
			<element name="RotationSpeed" type="string" />
			<element name="TurretRotationSpeed" type="string" />
			<element name="TurretTexture" type="string" />
			<element name="Texture" type="string" />
			<element name="Picture" type="string" />
		</sequence>
	</complexType>
	<complexType name="BuildingData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="Name" type="string" />
			<element name="Cost" type="string" />
			<element name="FireRange" type="string" />
			<element name="ReloadTime" type="string" />
			<element name="Health" type="string" />
			<element name="ViewRange" type="string" />
			<element name="Power" type="string" />
			<element name="BuildSpeed" type="string" />
			<element name="Texture" type="string" />
			<element name="Picture" type="string" />
			<element name="Size" type="tns:Size" />
			<element name="EnergyConsumption" type="string" />
			<element name="RideableFields" type="tns:RideableFields" />
			<element name="CanProduceUnits" type="tns:CanProduceUnits" />
			<element name="CanProduceBuilding"
				type="tns:CanProduceUnits" />
		</sequence>
	</complexType>
	<complexType name="Size">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="X" type="string" />
			<element name="Y" type="string" />
		</sequence>
	</complexType>
	<complexType name="RideableFields">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="int" type="string" />
		</sequence>
	</complexType>
	<complexType name="CanProduceUnits">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="name" type="string" />
		</sequence>
	</complexType>
	<complexType name="CanProduceBuildings">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="name" type="string" />
		</sequence>
	</complexType>
	<complexType name="UnitsData">
		<sequence>
			<element name="UnitData" type="tns:UnitData" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="BuildingsData">
		<sequence>
			<element name="BuildingData" type="tns:BuildingData"
				minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<element name="GameSettings" type="tns:GameSettings" />
	<complexType name="GameSettings">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="UnitsData" type="tns:UnitsData" />
			<element name="BuildingsData" type="tns:BuildingsData" />
		</sequence>
	</complexType>
</schema>

=== nowackia/yad2/branches/20070110-release/tmp/nowackia/dune_OLD.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:GameSettings xmlns:tns="http://www.example.org/dune" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/dune dune.xsd ">
  <tns:UnitsData>
    <tns:UnitData>
      <tns:Name>tns:Name</tns:Name>
      <tns:BaseType>tns:BaseType</tns:BaseType>
      <tns:Cost>tns:Cost</tns:Cost>
      <tns:FireRange>tns:FireRange</tns:FireRange>
      <tns:Speed>tns:Speed</tns:Speed>
      <tns:ReloadTime>tns:ReloadTime</tns:ReloadTime>
      <tns:AmmoType>tns:AmmoType</tns:AmmoType>
      <tns:Health>tns:Health</tns:Health>
      <tns:ViewRange>tns:ViewRange</tns:ViewRange>
      <tns:Power>tns:Power</tns:Power>
      <tns:BuildSpeed>tns:BuildSpeed</tns:BuildSpeed>
      <tns:DamageDestroy>tns:DamageDestroy</tns:DamageDestroy>
      <tns:RotationSpeed>tns:RotationSpeed</tns:RotationSpeed>
      <tns:TurretRotationSpeed>tns:TurretRotationSpeed</tns:TurretRotationSpeed>
      <tns:TurretTexture>tns:TurretTexture</tns:TurretTexture>
      <tns:Texture>tns:Texture</tns:Texture>
      <tns:Picture>tns:Picture</tns:Picture>
    </tns:UnitData>
  </tns:UnitsData>
  <tns:BuildingsData>
    <tns:BuildingData>
      <tns:Name>tns:Name</tns:Name>
      <tns:Cost>tns:Cost</tns:Cost>
      <tns:FireRange>tns:FireRange</tns:FireRange>
      <tns:ReloadTime>tns:ReloadTime</tns:ReloadTime>
      <tns:Health>tns:Health</tns:Health>
      <tns:ViewRange>tns:ViewRange</tns:ViewRange>
      <tns:Power>tns:Power</tns:Power>
      <tns:BuildSpeed>tns:BuildSpeed</tns:BuildSpeed>
      <tns:Texture>tns:Texture</tns:Texture>
      <tns:Picture>tns:Picture</tns:Picture>
      <tns:Size>
        <tns:X>tns:X</tns:X>
        <tns:Y>tns:Y</tns:Y>
      </tns:Size>
      <tns:EnergyConsumption>tns:EnergyConsumption</tns:EnergyConsumption>
      <tns:RideableFields>
        <tns:int>tns:int</tns:int>
      </tns:RideableFields>
      <tns:CanProduceUnits>
        <tns:name>tns:name</tns:name>
      </tns:CanProduceUnits>
      <tns:CanProduceBuilding>
        <tns:name>tns:name</tns:name>
      </tns:CanProduceBuilding>
    </tns:BuildingData>
  </tns:BuildingsData>
</tns:GameSettings>
