=== nowackia/yad2/trunk/src/Common/Config/dune.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/dune" attributeFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/dune" elementFormDefault="qualified">
	<!-- Main types -->
	<complexType name="UnitTrooperData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="TypeID" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="TypeKind" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="Name" type="string"  />
			<element name="Cost" type="short" />
			<element name="FireRange" type="short" />
			<element name="FirePower" type="short" />
			<element name="Speed" type="short" />
			<element name="ReloadTime" type="short" />
			<element name="AmmoType" type="string" />
			<element name="Health" type="short" />
			<element name="ViewRange" type="short" />
			<element name="BuildSpeed" type="short" />
			<element name="DamageDestroy" type="short" />
			<element name="RotationSpeed" type="short" />
			<element name="Size" type="float" />
		</sequence>
	</complexType>
	<complexType name="UnitTankData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="TypeID" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="TypeKind" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="Name" type="string" />
			<element name="Cost" type="short" />
			<element name="FireRange" type="short" />
			<element name="FirePower" type="short" />
			<element name="Speed" type="short" />
			<element name="ReloadTime" type="short" />
			<element name="AmmoType" type="string" />
			<element name="Health" type="short" />
			<element name="ViewRange" type="short" />
			<element name="BuildSpeed" type="short" />
			<element name="DamageDestroy" type="short" />
			<element name="RotationSpeed" type="short" />
			<element name="TurretRotationSpeed" type="short" />
			<element name="Size" type="float" />
		</sequence>
	</complexType>
	<complexType name="UnitHarvesterData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="TypeID" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="TypeKind" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="Name" type="string" />
			<element name="Cost" type="short" />
			<element name="Speed" type="short" />
			<element name="Health" type="short" />
			<element name="ViewRange" type="short" />
			<element name="BuildSpeed" type="short" />
			<element name="DamageDestroy" type="short" />
			<element name="RotationSpeed" type="short" />
			<element name="Capacity" type="short" />
			<element name="HarvestingSpeed" type="short" />
			<element name="Size" type="float" />
		</sequence>
	</complexType>
	<complexType name="UnitMCVData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="TypeID" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="TypeKind" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="Name" type="string" />
			<element name="Cost" type="short" />
			<element name="Speed" type="short" />
			<element name="Health" type="short" />
			<element name="ViewRange" type="short" />
			<element name="BuildSpeed" type="short" />
			<element name="DamageDestroy" type="short" />
			<element name="RotationSpeed" type="short" />
			<element name="BuildingCanProduce" type="string" />
			<element name="Size" type="float" />
		</sequence>
	</complexType>
	<complexType name="UnitSandwormData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="TypeID" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="TypeKind" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="Name" type="string" />
			<element name="Speed" type="short" />
			<element name="Health" type="short" />
			<element name="FirePower" type="short" />
			<element name="DamageDestroy" type="short" />
			<element name="RotationSpeed" type="short" />
			<element name="Size" type="float" />
		</sequence>
	</complexType>
	<complexType name="BuildingData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="TypeID" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="Name" type="string" />
			<element name="Cost" type="short" />
			<element name="Health" type="short" />
			<element name="ViewRange" type="short" />
			<element name="BuildSpeed" type="short" />
			<element name="Size" type="tns:Size" />
			<element name="EnergyConsumption" type="int" />
			<element name="TextureSpecialActionFramesCount" type="short" />
			<element name="TextureAnimationFramesCount" type="short" />
			<!--  For buildings with firing capability -->
			<element name="IsTurret" type="boolean" />
			<element name="FireRange" type="short" minOccurs="0" maxOccurs="1" default="0"/>
			<element name="FirePower" type="short" minOccurs="0" maxOccurs="1" default="0"/>
			<element name="ReloadTime" type="short" minOccurs="0" maxOccurs="1" default="0"/>
			<!-- -->
			<element name="RideableFields" type="tns:RideableFields" minOccurs="0" maxOccurs="1" />
			<element name="UnitsCanProduce" type="tns:UnitsNames" minOccurs="0" maxOccurs="1" />
			<element name="BuildingsCanProduce" type="tns:BuildingsNames" minOccurs="0" maxOccurs="1" />
			
		</sequence>
	</complexType>
	<complexType name="AmmoData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="TypeID" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="Name" type="string" />
			<element name="Speed" type="short" />
			<element name="DamageDestroyRange" type="short" />
		</sequence>
	</complexType>
	<complexType name="RaceData">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="TypeID" type="short" minOccurs="0" maxOccurs="1"/>
			<element name="Name" type="string" />
			<element name="TechnologyDependences" type="tns:TechnologyDependences" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>
	<!-- Main types plural -->
	<complexType name="UnitTroopersData">
		<sequence>
			<element name="UnitTrooperData" type="tns:UnitTrooperData" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="UnitTanksData">
		<sequence>
			<element name="UnitTankData" type="tns:UnitTankData" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="UnitHarvestersData">
		<sequence>
			<element name="UnitHarvesterData" type="tns:UnitHarvesterData" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="UnitMCVsData">
		<sequence>
			<element name="UnitMCVData" type="tns:UnitMCVData" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="UnitSandwormsData">
		<sequence>
			<element name="UnitSandwormData" type="tns:UnitSandwormData" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="BuildingsData">
		<sequence>
			<element name="BuildingData" type="tns:BuildingData" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="AmmosData">
		<sequence>
			<element name="AmmoData" type="tns:AmmoData" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="RacesData">
		<sequence>
			<element name="RaceData" type="tns:RaceData" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<!-- Auxiliary types -->
	<complexType name="TechnologyDependences">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="TechnologyDependence" type="tns:TechnologyDependence" />
		</sequence>
	</complexType>
	<complexType name="TechnologyDependence">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="BuildingName" type="string" />
			<element name="RequiredBuildings" type="tns:BuildingsNames" />
		</sequence>
	</complexType>
	<complexType name="BuildingsNames">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="Name" type="string" />
		</sequence>
	</complexType>
	<complexType name="Size">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="X" type="short" />
			<element name="Y" type="short" />
		</sequence>
	</complexType>
	<complexType name="RideableFields">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="index" type="short" />
		</sequence>
	</complexType>
	<complexType name="UnitsNames">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="Name" type="string" />
		</sequence>
	</complexType>
	<!-- Game Settings main type -->
	<element name="GameSettings" type="tns:GameSettings" />
	<complexType name="GameSettings">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="UnitTroopersData" type="tns:UnitTroopersData" />
			<element name="UnitTanksData" type="tns:UnitTanksData" />
			<element name="UnitHarvestersData" type="tns:UnitHarvestersData" />
			<element name="UnitMCVsData" type="tns:UnitMCVsData" />
			<element name="UnitSandwormsData" type="tns:UnitSandwormsData" />
			<element name="AmmosData" type="tns:AmmosData" />
			<element name="BuildingsData" type="tns:BuildingsData" />
			<element name="RacesData" type="tns:RacesData" />
		</sequence>
	</complexType>
</schema>

=== nowackia/yad2/trunk/src/Resources/dune_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:GameSettings xmlns:tns="http://www.example.org/dune" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/dune dune.xsd ">

  <tns:UnitTroopersData>
    <tns:UnitTrooperData>
      <tns:Name>Infantry</tns:Name>
      <tns:Cost>100</tns:Cost>
      <tns:FireRange>5</tns:FireRange>
      <tns:Speed>2</tns:Speed>
      <tns:ReloadTime>2</tns:ReloadTime>
      <tns:AmmoType>Bullet</tns:AmmoType>
      <tns:Health>100</tns:Health>
      <tns:ViewRange>10</tns:ViewRange>
      <tns:Power>50</tns:Power>
      <tns:BuildSpeed>10</tns:BuildSpeed>
      <tns:DamageDestroy>5</tns:DamageDestroy>
      <tns:RotationSpeed>1</tns:RotationSpeed>
      <tns:Texture>Unit_Infantry</tns:Texture>
      <tns:Picture>Picture_Infantry</tns:Picture>
    </tns:UnitTrooperData>
  </tns:UnitTroopersData>
  
  <tns:UnitTanksData>
    <tns:UnitTankData>
      <tns:Name>Tank</tns:Name>
      <tns:Cost>100</tns:Cost>
      <tns:FireRange>10</tns:FireRange>
      <tns:Speed>4</tns:Speed>
      <tns:ReloadTime>3</tns:ReloadTime>
      <tns:AmmoType>Bullet</tns:AmmoType>
      <tns:Health>100</tns:Health>
      <tns:ViewRange>10</tns:ViewRange>
      <tns:Power>30</tns:Power>
      <tns:BuildSpeed>10</tns:BuildSpeed>
      <tns:DamageDestroy>10</tns:DamageDestroy>
      <tns:RotationSpeed>2</tns:RotationSpeed>
      <tns:TurretRotationSpeed>1</tns:TurretRotationSpeed>
      <tns:TurretTexture>Unit_TankTurret</tns:TurretTexture>
      <tns:Texture>Unit_TankBase</tns:Texture>
      <tns:Picture>Picture_Tank</tns:Picture>
    </tns:UnitTankData>
  </tns:UnitTanksData>
  
  <tns:UnitHarvestersData>
    <tns:UnitHarvesterData>
      <tns:Name>Harvester</tns:Name>
      <tns:Cost>300</tns:Cost>
      <tns:Speed>3</tns:Speed>
      <tns:Health>100</tns:Health>
      <tns:ViewRange>5</tns:ViewRange>
      <tns:BuildSpeed>10</tns:BuildSpeed>
      <tns:DamageDestroy>5</tns:DamageDestroy>
      <tns:RotationSpeed>2</tns:RotationSpeed>
      <tns:Capacity>150</tns:Capacity>
      <tns:GatheringSpeed>20</tns:GatheringSpeed>
      <tns:Texture>Unit_Harvester</tns:Texture>
      <tns:Picture>Picture_Harvester</tns:Picture>
    </tns:UnitHarvesterData>
  </tns:UnitHarvestersData>
  
  <tns:UnitMCVsData>
    <tns:UnitMCVData>
      <tns:Name>MCV</tns:Name>
      <tns:Cost>400</tns:Cost>
      <tns:Speed>10</tns:Speed>
      <tns:Health>150</tns:Health>
      <tns:ViewRange>5</tns:ViewRange>
      <tns:BuildSpeed>15</tns:BuildSpeed>
      <tns:DamageDestroy>20</tns:DamageDestroy>
      <tns:RotationSpeed>4</tns:RotationSpeed>
      <tns:BuildingCanProduce>Barracks</tns:BuildingCanProduce>
      <tns:Texture>Unit_MCV</tns:Texture>
      <tns:Picture>Picture_MCV</tns:Picture>
    </tns:UnitMCVData>
  </tns:UnitMCVsData>
  
  <tns:UnitSandwormsData>
    <tns:UnitSandwormData>
      <tns:Name>Sandworm</tns:Name>
      <tns:Speed>1</tns:Speed>
      <tns:Health>100</tns:Health>
      <tns:Power>5000</tns:Power>
      <tns:DamageDestroy>0</tns:DamageDestroy>
      <tns:RotationSpeed>0</tns:RotationSpeed>
      <tns:Texture>Unit_Sandworm</tns:Texture>
    </tns:UnitSandwormData>
  </tns:UnitSandwormsData>
  
  <tns:AmmosData>
    <tns:AmmoData>
      <tns:Name>Bullet</tns:Name>
      <tns:Speed>0</tns:Speed>
      <tns:DamageDestroyRange>0</tns:DamageDestroyRange>
    </tns:AmmoData>
  </tns:AmmosData>
  
  <tns:BuildingsData>
    <tns:BuildingData>
      <tns:Name>Barracks</tns:Name>
      <tns:Cost>100</tns:Cost>
      <tns:Health>1000</tns:Health>
      <tns:ViewRange>10</tns:ViewRange>
      <tns:BuildSpeed>25</tns:BuildSpeed>
      <tns:Texture>Structure_Barracks</tns:Texture>
      <tns:Picture>Picture_Barracks</tns:Picture>
      <tns:Size>
        <tns:X>2</tns:X>
        <tns:Y>2</tns:Y>
      </tns:Size>
      <tns:EnergyConsumption>100</tns:EnergyConsumption>
      <tns:RideableFields>
        <tns:index>3</tns:index>
      </tns:RideableFields>
      <tns:UnitsCanProduce>
        <tns:Name>Infantry</tns:Name>
      </tns:UnitsCanProduce>
    </tns:BuildingData>
  </tns:BuildingsData>
  
  <tns:RacesData>
    <tns:RaceData>
      <tns:Name>Atreides</tns:Name>
    </tns:RaceData>
    <tns:RaceData>
      <tns:Name>Harkonnen</tns:Name>
    </tns:RaceData>
  </tns:RacesData>
</tns:GameSettings>
